  name: Pedro Ferreira da Costa, PhD Researcher
  markdown: kramdown

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-hacker
permalink: /blog/:title